name = "thread-again"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
